export enum EVENT_ENUM {
  NEXT_LEVEL = 'NEXT_LEVEL',
  PLAYER_CONTROL = 'PLAYER_CONTROL',
  PLAYER_MOVE_END = 'PLAYER_MOVE_END',
  PLAYER_DEATH = 'PLAYER_DEATH',
  ENEMY_DEATH = 'ENEMY_DEATH',
  PLAYER_BORN = 'PLAYER_BORN',
  DOOR_OPEN = 'DOOR_OPEN',
}

/***
 * 有限状态机参数类型枚举
 */
export enum FSM_PARAM_TYPE_ENUM {
  NUMBER = 'NUMBER',
  TRIGGER = 'TRIGGER',
}

export enum PARAMS_NAME_ENUM {
  IDLE = 'IDLE',
  TURN_LEFT = 'TURN_LEFT',
  TURN_RIGHT = 'TURN_RIGHT',
  DIRECTION = 'DIRECTION',
  BLOCK_LEFT = 'BLOCK_LEFT',
  BLOCK_UP = 'BLOCK_UP',
  BLOCK_BOTTOM = 'BLOCK_BOTTOM',
  BLOCK_RIGHT = 'BLOCK_RIGHT',
  BLOCK_TURN_LEFT = 'BLOCK_TURN_LEFT',
  BLOCK_TURN_RIGHT = 'BLOCK_TURN_RIGHT',
  ATTACK = 'ATTACK',
  DEATH = 'DEATH',
  AIRDEATH = 'AIRDEATH',
}

export enum DIRECTION_ENUM {
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
  UP = 'UP',
  BOTTOM = 'BOTTOM',
}

export enum ENTITY_STATE_ENUM {
  IDLE = 'IDLE',
  ATTACK = 'ATTACK',
  TURNLEFT = 'TURNLEFT',
  TURNRIGHT = 'TURNRIGHT',
  BLOCKFRONT = 'BLOCKFRONT',
  BLOCKBACK = 'BLOCKBACK',
  BLOCKLEFT = 'BLOCKLEFT',
  BLOCKRIGHT = 'BLOCKRIGHT',
  BLOCKTURNLEFT = 'BLOCKTURNLEFT',
  BLOCKTURNRIGHT = 'BLOCKTURNRIGHT',
  DEATH = 'DEATH',
  AIRDEATH = 'AIRDEATH',
  OPEN = 'OPEN',
}

export enum CONTROLLER_ENUM {
  UP = 'UP',
  BOTTOM = 'BOTTOM',
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
  TURN_LEFT = 'TURN_LEFT',
  TURN_RIGHT = 'TURN_RIGHT',
}

export enum ENTITY_TYPE_ENUM {
  DOOR = 'DOOR',
  PLAYER = 'PLAYER',
  WOODENSKELETON = 'WOODENSKELETON',
  IRONSKELETON = 'IRONSKELETON',
}

export enum DIRECTION_ORDER_ENUM {
  UP = 0,
  BOTTOM = 1,
  LEFT = 2,
  RIGHT = 3,
}

export enum SPIKES_SUBSTATE_TYPE {
  ZERO = 'ZERO',
  ONE = 'ONE',
  TWO = 'TWO',
  THREE = 'THREE',
  FOUR = 'FOUR',
  FIVE = 'FIVE',
}

export enum SPIKES_SUBSTATE_ORDER_ENUM {
  ZERO = 0,
  ONE = 1,
  TWO = 2,
  THREE = 3,
  FOUR = 4,
  FIVE = 5,
}

export enum SPIKES_TYPE {
  SPIKES_ONE = 'SPIKES_ONE',
  SPIKES_TWO = 'SPIKES_TWO',
  SPIKES_THREE = 'SPIKES_THREE',
  SPIKES_FOUR = 'SPIKES_FOUR',
}

export enum SPIKES_PARAMS_ENUM {
  SPIKES_STEP = 'SPIKES_STEP',
  SPIKES_TYPE = 'SPIKES_TYPE',
}
